name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.10.0

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_remote_config: ^2.0.0
  image_picker: ^0.8.4+8
  intl: ^0.17.0
  drift: ^1.4.0
  drift_inspector: ^1.0.0
  path_provider: ^2.0.9
  package_info_plus: ^1.3.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  sqlite3_flutter_libs: ^0.5.3
  unsplash_client: ^2.1.0+1
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  lints: ^1.0.1
  mockito: ^5.1.0
  drift_dev: ^1.4.0
  network_image_mock: ^2.0.1
  transparent_image: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
