name: flauncher
description: Flutter-based Android TV launcher.

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.7.5

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.15
  firebase_remote_config: ^3.0.13
  image_picker: ^0.8.6+3
  intl: ^0.18.0
  drift: ^2.5.0
  path_provider: ^2.0.13
  package_info_plus: ^3.0.3
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  sqlite3_flutter_libs: ^0.5.13
  unsplash_client: ^2.1.0+3
  webview_flutter: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  lints: ^1.0.1
  mockito: ^5.3.2
  drift_dev: ^2.5.2
  network_image_mock: ^2.1.1
  transparent_image: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
